### PR TITLE
Add gitlab API

### PR DESCRIPTION
**Pull request by jezhodges**
Adds support for Gitlab repositories

### CODE REVIEW

**Comment by jezhodges** [comment]
Cc'ing @foosin

**Comment by foosinn** [comment]
Nice work @jezhodges!

I'll update our test environment during the week and merge afterwards. Thanks!

**Comment by foosinn** [comment]
Hey, any reason why you went with after~1 instead of master? May the default branch is the right thing to use here?

**Comment by jezhodges** [comment]
@foosinn if you are updating master directly, you cannot compare a SHA ref and master as master will be the latest.

So `sha ref` -> merge to master -> `master` so you can't compare, certainly in the Gitlab API.

**Comment by foosinn** [comment]
Good catch!

**Pull request merged**
